version: "3"
services:
  app:
    build: .
    ports:
      - ${LOCAL_PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres
    command:
      - sh
      - -c
      - python -m main
        
    networks:
      - app-network

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge