"""Add SKU to product

Revision ID: 1ecb4422f8e9
Revises: 7b80efb7236f
Create Date: 2025-05-14 07:50:11.781994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecb4422f8e9'
down_revision: Union[str, None] = '7b80efb7236f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
