"""Add bundle type

Revision ID: 1f777a01381b
Revises: 7b072c558a01
Create Date: 2025-05-19 06:54:28.066181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.enums import BundleTypeEnum


# revision identifiers, used by Alembic.
revision: str = "1f777a01381b"
down_revision: Union[str, None] = "7b072c558a01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE bundletypeenum AS ENUM ('NONE', 'DIY');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "bundle_type",
            sa.Enum(BundleTypeEnum, name="bundletypeenum"),
            nullable=False,
            default=BundleTypeEnum.DIY,
        ),
    )
    op.drop_column("products", "is_bundle")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE bundletypeenum")
    op.add_column(
        "products",
        sa.Column("is_bundle", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("products", "bundle_type")
    # ### end Alembic commands ###
