"""Unique subcategory title

Revision ID: 27b98cde69d7
Revises: 7c437fcc5b17
Create Date: 2025-05-19 09:16:29.132584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27b98cde69d7"
down_revision: Union[str, None] = "7c437fcc5b17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "subcategories", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subcategories", type_="unique")
    # ### end Alembic commands ###
