"""Add subcategory model

Revision ID: 36c4017b4b4f
Revises: c0599329890a
Create Date: 2025-05-06 13:42:31.626732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c4017b4b4f'
down_revision: Union[str, None] = 'c0599329890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('display_title', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='SubCategoryParentFK', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('uq_main_image_per_product', table_name='images', postgresql_where='(is_main = true)')
    op.add_column('products', sa.Column('subcategory_id', sa.UUID(), nullable=True))
    op.create_foreign_key('SubCategoryProductFK', 'products', 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SubCategoryProductFK', 'products', type_='foreignkey')
    op.drop_column('products', 'subcategory_id')
    op.create_index('uq_main_image_per_product', 'images', ['product_id'], unique=True, postgresql_where='(is_main = true)')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
