"""Add constructor table

Revision ID: 4dd822638f20
Revises: 2d798b756d61
Create Date: 2025-04-02 13:15:09.937022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dd822638f20'
down_revision: Union[str, None] = '2d798b756d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_constructor',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('TOP_BANNER', 'BOTTOM_BANNER', 'ACCORDION', name='constructortag'), nullable=False),
    sa.Column('constructor_type', sa.Enum('BANNER', 'BUTTON', 'TEXT', name='constructortype'), nullable=False),
    sa.Column('component_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_constructor')
    # ### end Alembic commands ###
