"""Add product indexes

Revision ID: 7b072c558a01
Revises: 1ecb4422f8e9
Create Date: 2025-05-19 06:45:23.870933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b072c558a01'
down_revision: Union[str, None] = '1ecb4422f8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_available_only', 'products', ['category_id', sa.text('create_at DESC')], unique=False, postgresql_where=sa.text('is_available = TRUE'))
    op.create_index('idx_products_cat_available_created', 'products', ['subcategory_id', 'is_available', sa.text('create_at DESC')], unique=False)
    op.create_index('idx_products_manufacturer_id', 'products', ['manufacturer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_manufacturer_id', table_name='products')
    op.drop_index('idx_products_cat_available_created', table_name='products')
    op.drop_index('idx_products_available_only', table_name='products', postgresql_where=sa.text('is_available = TRUE'))
    # ### end Alembic commands ###
