"""Update attributes model

Revision ID: c2db32b6e220
Revises: 36c4017b4b4f
Create Date: 2025-05-07 14:41:19.553581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.enums import AttributeGroupEnum


# revision identifiers, used by Alembic.
revision: str = 'c2db32b6e220'
down_revision: Union[str, None] = '36c4017b4b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

attribute_group_enum = postgresql.ENUM(
    *[e.name for e in AttributeGroupEnum],
    name="attribute_group_enum"
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_attribute', if_exists=True)

    attribute_group_enum.create(op.get_bind())
    op.add_column('attributes', sa.Column('attribute_group', sa.Enum('TASTE', 'VOLUME', 'COUNTRY', 'COLOR', 'TASTE_GROUP', 'BRAND', name='attribute_group_enum'), nullable=False))
    op.add_column('attributes', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('attributes', sa.Column('price_modifier', sa.DECIMAL(), nullable=True))
    op.add_column('attributes', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key('AttributeProductFK', 'attributes', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attributes', 'title')
    op.add_column('images', sa.Column('attribute_id', sa.UUID(), nullable=True))
    op.alter_column('images', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'images', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    attribute_group_enum.drop(op.get_bind())
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.alter_column('images', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('images', 'attribute_id')
    op.add_column('attributes', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('AttributeProductFK', 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'product_id')
    op.drop_column('attributes', 'price_modifier')
    op.drop_column('attributes', 'stock_quantity')
    op.drop_column('attributes', 'attribute_group')
    op.create_table('product_attribute',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attribute_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='product_attribute_attribute_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_attribute_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id', name='product_attribute_pkey')
    )
    # ### end Alembic commands ###
